In [19]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report
import re
import string

In [20]:
train_df = pd.read_csv("train.csv", header=None)
test_df = pd.read_csv("test.csv", header=None)

train_df.columns = ['label', 'title', 'description']
test_df.columns = ['label', 'title', 'description']

In [21]:
train_df

,label,title,description
0,Class Index,Title,Description
1,3,Wall St. Bears Claw Back Into the Black (Reuters),"Reuters - Short-sellers, Wall Street's dwindli..."
2,3,Carlyle Looks Toward Commercial Aerospace (Reu...,Reuters - Private investment firm Carlyle Grou...
3,3,Oil and Economy Cloud Stocks' Outlook (Reuters),Reuters - Soaring crude prices plus worries\ab...
4,3,Iraq Halts Oil Exports from Main Southern Pipe...,Reuters - Authorities have halted oil export\f...
...,...,...,...
119996,1,Pakistan's Musharraf Says Won't Quit as Army C...,KARACHI (Reuters) - Pakistani President Perve...
119997,2,Renteria signing a top-shelf deal,Red Sox general manager Theo Epstein acknowled...
119998,2,Saban not going to Dolphins yet,The Miami Dolphins will put their courtship of...
119999,2,Today's NFL games,PITTSBURGH at NY GIANTS Time: 1:30 p.m. Line: ...
120000,2,Nets get Carter from Raptors,INDIANAPOLIS -- All-Star Vince Carter was trad...

In [22]:
test_df

,label,title,description
0,Class Index,Title,Description
1,3,Fears for T N pension after talks,Unions representing workers at Turner Newall...
2,4,The Race is On: Second Private Team Sets Launc...,"SPACE.com - TORONTO, Canada -- A second\team o..."
3,4,Ky. Company Wins Grant to Study Peptides (AP),AP - A company founded by a chemistry research...
4,4,Prediction Unit Helps Forecast Wildfires (AP),AP - It's barely dawn when Mike Fitzpatrick st...
...,...,...,...
7596,1,Around the world,Ukrainian presidential candidate Viktor Yushch...
7597,2,Void is filled with Clement,With the supply of attractive pitching options...
7598,2,Martinez leaves bitter,Like Roger Clemens did almost exactly eight ye...
7599,3,5 of arthritis patients in Singapore take Bext...,SINGAPORE : Doctors in the United States have ...
7600,3,EBay gets into rentals,EBay plans to buy the apartment and home renta...

# STEP 3: Combine Title & Description

In [23]:
train_df['text'] = train_df['title'] + " " + train_df['description']
test_df['text'] = test_df['title'] + " " + test_df['description']

# STEP 4: Text Preprocessing

# Create Preprocessing Function

In [24]:
def clean_text(text):
    text = text.lower()                      # lowercase
    text = re.sub(r'\d+', '', text)           # remove numbers
    text = text.translate(str.maketrans('', '', string.punctuation))  # remove punctuation
    text = text.strip()                       # remove extra spaces
    return text

# Apply Preprocessing

In [25]:
train_df['text'] = train_df['text'].apply(clean_text)
test_df['text'] = test_df['text'].apply(clean_text)

# STEP 5: Split Input & Output

In [26]:
X_train = train_df['text']
y_train = train_df['label']

X_test = test_df['text']
y_test = test_df['label']

# STEP 6: Convert Text to Numbers (TF-IDF)

In [27]:
vectorizer = TfidfVectorizer(stop_words='english', max_features=3000)

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

# MODEL 1: Multinomial Naive Bayes

In [28]:
nb = MultinomialNB()
nb.fit(X_train_vec, y_train)

nb_pred = nb.predict(X_test_vec)

print("Naive Bayes Accuracy:", accuracy_score(y_test, nb_pred))

Naive Bayes Accuracy: 0.8825154584923036

# MODEL 2: Logistic Regression

In [29]:
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train_vec, y_train)


lr_pred = lr.predict(X_test_vec)

print("Logistic Regression Accuracy:", accuracy_score(y_test, lr_pred))

Logistic Regression Accuracy: 0.8964609919747402

# MODEL 3: Random Forest

In [ ]:
rf = RandomForestClassifier(n_estimators=100)
rf.fit(X_train_vec, y_train)

rf_pred = rf.predict(X_test_vec)

print("Random Forest Accuracy:", accuracy_score(y_test, rf_pred))

# STEP 7: Classification Report

In [ ]:
print("Naive Bayes Report\n", c
      lassification_report(y_test, nb_pred))
print("Logistic Regression Report\n", classification_report(y_test, lr_pred))
print("Random Forest Report\n", classification_report(y_test, rf_pred))

# Visualization: Model Accuracy Comparison

In [ ]:
nb_acc = accuracy_score(y_test, nb_pred)
lr_acc = accuracy_score(y_test, lr_pred)
rf_acc = accuracy_score(y_test, rf_pred)

In [ ]:
import matplotlib.pyplot as plt

models = ['Naive Bayes', 'Logistic Regression', 'Random Forest']
accuracy = [nb_acc, lr_acc, rf_acc]

plt.figure()
plt.bar(models, accuracy)
plt.xlabel('Models')
plt.ylabel('Accuracy')
plt.title('Model Comparison for News Classification')
plt.ylim(0, 1)

plt.show()